name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build project
      run: make build

    - name: Install the tool
      run: sudo make install

    - name: Run organize_pdfs
      run: organize_pdfs --root /home/runner/work/organize_pdfs/root_folder --report
